### ISSUE TITLE
Weekly Tasks

### ISSUE THREAD

**Issue by ctiProgramming1** [O115sama/Rwaity#1]
1. Add Book Screen.
2. Add User Screen.
3. Update GitHub Readme.md
4. Design ERD Database.
5. Mobile Screens (Responsive Design).

**Comment by ctiProgramming1** [comment]
~~1. Add Book Screen.
2. Add User Screen.~~
**3. Update GitHub Readme.md
4. Design ERD Database.
5. Mobile Screens (Responsive Design).**

**Comment by ctiProgramming1** [comment]
**- Implement the main page(index.php)
- install apache server with php support (Example wamp server)**

**Comment by O115sama** [comment]
~~1. Add Book Screen.
2. Add User Screen.
3. Update GitHub Readme.md
4. Design ERD Database.
5. Mobile Screens (Responsive Design).
6. install apache server with php support (Example wamp server)~~

**Comment by ctiProgramming1** [comment]
1. Implement all pages.
2. Implement the database .
3. Implement git environment.

**Comment by ctiProgramming1** [comment]
4. Readme.md

**Comment by ctiProgramming1** [comment]
### Connect all pages to the database.
